import { draftMode } from 'next/headers'
import './globals.css'
import { Inter } from 'next/font/google'
import LiveVisualEditing from './_components/LiveVisualEditing'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-sky-600 text-white">
          <div className="container mx-auto px-4 py-4 w-full">Apptiva</div>
        </header>
        {children}
        {draftMode().isEnabled && <LiveVisualEditing />}
      </body>
    </html>
  )
}
